name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]

# allow applying labels from base repo
permissions:
  contents: read
  pull-requests: write
  # add this only if you want the action to auto-create labels (sync-labels: true)
  # issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: false   # set true if you want it to create missing labels
